name: Lint Code and Deploy

on: 
  push:  # Runs on every push to any branch
  pull_request:  # Also runs on pull requests

jobs:
  lint:
    name: Lint Python code, generate static files and deploy to GH Pages repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort flake8
          pip install -r requirements.txt

      - name: Check isort compliance
        run: isort --check-only --diff pelicanconf.py publishconf.py tasks.py

      - name: Check PEP 8 compliance with Flake8
        run: flake8 --max-line-length=120 pelicanconf.py publishconf.py tasks.py

      - name: Generate Pelican Static Files
        run: |
          pelican content -o output -s pelicanconf.py

      - name: Set up SSH for Pushing to Another Repo
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push content directory into the GH Pages repo
        run: |
          git clone git@github.com:gzrubio/gzrubio.github.io.git tmp_repo
          cp -r output/* tmp_repo/
          cd tmp_repo
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Automated update from GitHub Actions" || echo "No changes to commit"
          git push origin main
